# Generated by Django 3.1.3 on 2020-11-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201118_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='developer.jpg', null=True, upload_to='profile_img'),
        ),
    ]
