# Generated by Django 3.1.3 on 2020-11-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201118_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='', upload_to='profile_img'),
            preserve_default=False,
        ),
    ]
