# Generated by Django 3.1.3 on 2020-11-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201118_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skils',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
